export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_SHOP_PRODUCT = "FETCH_SHOP_PRODUCT";
export const FETCH_FEATURED_PRODUCT_LIST = "FETCH_FEATURED_PRODUCT_LIST";
export const FETCH_FEATURED_PRODUCT_DETAIL = "FETCH_FEATURED_PRODUCT_DETAIL";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DECREASE_PRODUCT_FROM_CART = "DECREASE_PRODUCT_FROM_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAN_CART = "CLEAN_CART";



