export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";
export const FETCH_SHOP_PRODUCT = "FETCH_SHOP_PRODUCT";
export const FETCH_FEATURED_PRODUCT_LIST = "FETCH_FEATURED_PRODUCT_LIST";
export const FETCH_FEATURED_PRODUCT_DETAIL = "FETCH_FEATURED_PRODUCT_DETAIL";

export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";



